# Workflow for publishing docker image to GitHub Container Registry

name: Publish to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract current version
        id: extract_version
        run: echo version=$(cat VERSION) >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    ## Always push latest until we change our minds:
    #   - name: Check if image exists using docker inspect
    #     id: check_image
    #     run: docker manifest inspect ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.version }} > /dev/null && echo "exists=true" || echo "exists=false" >> $GITHUB_OUTPUT
    #     if: steps.check_image.outputs.exists == 'false'

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.version }}
