name: test workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #what is v2?
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          docker pull myrtopar/autoexploit:latest
        
      - run: |
          docker run --rm --privileged \
          -v ${{ github.workspace }}/auto_bof.py:/app/auto_bof.py \
          myrtopar/autoexploit:latest \
          /bin/bash -c "echo 'lalala'"
          
