name: test workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #what is v2?
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          docker pull myrtopar/autoexploit:latest
        
      - run: |
          docker run --rm --privileged \
          -v ${{ github.workspace }}/src:/app/src \
          -v ${{ github.workspace }}/tests:/app/tests \
          myrtopar/autoexploit:latest \
          python3 -m pytest tests/test_exploit.py::test_exploit
          
