name: test workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: run trivial test
        run: |
          echo "running for test purposes"
          echo "done"
