name: Functional Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish to GHCR"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: |
          docker pull ghcr.io/myrtopar/pivot:0.1

      - run: |
          docker run --rm --privileged \
          -v ${{ github.workspace }}/:/app/ \
          ghcr.io/myrtopar/pivot:0.1 \
          pytest tests/test_exploit.py --junitxml=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
