name: test workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #what is v2?
      - name: Checkout code
        uses: actions/checkout@v2

      #is docker buildx really necassary???
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t autoexploit .
        
      - name: Run a simple command in Docker
        run: |
          docker run --rm --privileged \
          -v ${{ github.workspace }}/auto_bof.py:/app/auto_bof.py \
          -v ${{ github.workspace }}/binaries:/mnt/binaries \
          autoexploit \
          /bin/bash -c "echo 'lalala'"
          
